CREATE TABLE IF NOT EXISTS sleep_daily (
    date DATE NOT NULL,
    source TEXT NOT NULL DEFAULT 'garmin',
    sleep_start_at TIMESTAMPTZ,
    sleep_end_at TIMESTAMPTZ,
    total_seconds INTEGER,
    deep_seconds INTEGER,
    light_seconds INTEGER,
    rem_seconds INTEGER,
    awake_seconds INTEGER,
    nap_seconds INTEGER,
    unmeasurable_seconds INTEGER,
    score_overall INTEGER,
    score_qualifier TEXT,
    restless_moments INTEGER,
    avg_heart_rate INTEGER,
    avg_overnight_hrv NUMERIC,
    avg_respiration NUMERIC,
    resting_heart_rate INTEGER,
    body_battery_change INTEGER,
    avg_spo2 NUMERIC,
    lowest_spo2 NUMERIC,
    awake_count INTEGER,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (date, source)
);
